var list = [
    "Xiao",
    "Amber",
    "Yelan",
    "Ganyu",
    "Venti",
    "Paimon",
    "Kazuha",
    "Dendro",
    "Timmie",
    "MiHoYo",
    "Zhongli",
    "Celestia",
    "Primogem",
    "Katheryne",
    "Katheryne",
    "Snezhnaya",
    "Traveler",
    "Scaramouche",
    "Unknown God",
    "Spiral Abyss",
    "Liyue Qixing",
    "Memento Lens",
    "Raiden Shogun",
    "Dream Solvent",
    "Serenitea Pot",
    "Fragile Resin",
    "Staff of Homa",
    "Dust of Azoth",
    "Kamisato Ayaka",
    "Genesis Crystal",
    "Reckless Pallad",
    "Thundering Pulse",
    "Paimon's Bargains",
    "Portable Waypoint",
    "Knights of Favonius",
];